[package]
name = "br-eof-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#binread = "2.2.0"
binrw = "0.8.4"
